In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

<h1>Constant Value Tensors</h1>
<h2> Câu 1: Tạo một tensor có shape [2, 3] với tất cả các phần tử ban đầu = 0 </h2>

In [3]:
tensor = tf.zeros((2,3))

In [4]:
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<h2>Câu 2: Cho X là một tensor như sau [[1,2,3], [4,5,6]]. Tạo 1 tensor có cùng shape và dtype như X với các phần tử ban đầu = 0</h2>

In [5]:
tensor2_1 = tf.constant([[1,2,3],[4,5,6]],)

In [6]:
tensor2_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
tensor2_2 = tf.zeros(tensor2_1.shape)
tensor2_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<h2>Câu 3: Tạo một tensor có shape [2, 3] với tất cả các phần tử ban đầu là 1</h2>

In [8]:
tensor3 = tf.ones((2,3))
tensor3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<h2>Câu 4: Cho X là một tensor như sau [[1,2,3], [4,5,6]]. Tạo 1 tensor có cùng shape và dtype như X với các phần tử ban đầu = 1</h2>

In [9]:
tensor4_1 = tf.constant([[1,2,3],[4,5,6]])
tensor4_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [10]:
tensor4_2 = tf.ones(tensor4_1.shape)
tensor4_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<h2>Câu 5: Tạo một tensor có shape [3, 2] với tất cả các phần tử ban đầu là 5</h2>

In [11]:
tensor5 = tf.ones((3,2))*5

In [12]:
tensor5

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.],
       [5., 5.]], dtype=float32)>

<h2>Câu 6: Tạo một constant tensor [[1, 3, 5], [4, 6, 8]], dtype=float32</h2>

In [13]:
tensor6 = tf.constant([[1,3,5],[4,6,8]],dtype='float32')
tensor6

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 3., 5.],
       [4., 6., 8.]], dtype=float32)>

<h2>Câu 7: Tạo một constant tensor có shape [2, 3], với tất cả các phần tử ban đầu là 4</h2>

In [14]:
tensor7 = tf.ones((2,3))*4
tensor7

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

<h1>Sequence</h1>
<h2>Câu 1: Tạo 1-D tensor gồm 50 phần tử khoảng cách đều nhau từ 5 đến 10</h2>

In [15]:
tensorS_1 = tf.constant([x for x in range(51) if x%5 == 0])
tensorS_1

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])>

<h2>Câu 2: Tạo 1 tensor như sau: [10, 12, 14, 16, ..., 100]</h2>

In [16]:
tensorS_2 = tf.constant([x for x in range(101) if x >= 10 and x %2 == 0])
tensorS_2

<tf.Tensor: shape=(46,), dtype=int32, numpy=
array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])>

<h1>Random Tensor</h1>
<h2>Câu 1: Tạo một tensor ngẫu nhiên có shape [3, 2], với các phần tử từ phân bố chuẩn của giá
trị trung bình = 0 (normal distribution of mean), độ lệch chuẩn = 2 (standard deviation)</h2>

In [19]:
import random
import math
list_x = [random.gauss(0,2) for i in range(6)]
list_x

[4.224221244631331,
 -1.3348601642141702,
 4.947399467080647,
 0.7505069823240245,
 -0.9842961075146182,
 1.0857023487639779]

In [20]:
tensorR_1 = tf.constant(list_x,shape=(3,2))

In [21]:
tensorR_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 4.224221 , -1.3348602],
       [ 4.9473996,  0.750507 ],
       [-0.9842961,  1.0857023]], dtype=float32)>

<h2>Câu 2: Tạo một random tensor có shape [3, 2], với các phần tử nằm trong một uniform distribution trong khoảng từ 0 đến 2.</h2>

In [26]:
list_x2 = []
while len(list_x2) < 6:
    x = random.gauss(2,4)
    if x <= 2 and x>=0:
        list_x2.append(x)
list_x2

[0.8489060743117474,
 1.391054489613894,
 0.08624532481157465,
 0.6525202035660977,
 0.4876313481221013,
 0.4202519267515181]

In [ ]:
tem